# Generated by Django 3.1.1 on 2020-09-11 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaidik_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='desc',
            new_name='description',
        ),
    ]
