# Generated by Django 3.1.1 on 2020-09-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaidik_admin', '0003_auto_20200911_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('message', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='services',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
