# Generated by Django 3.1.1 on 2020-09-11 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaidik_admin', '0004_auto_20200911_1650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
