# Generated by Django 3.1.1 on 2020-09-12 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaidik_admin', '0006_contact_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='service',
            new_name='services',
        ),
    ]
