# Generated by Django 3.0.6 on 2020-09-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaidik_admin', '0007_auto_20200912_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=11)),
                ('address', models.CharField(default='', max_length=200)),
                ('pooja_date', models.DateField(default='')),
                ('select_pooja', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
