# Generated by Django 3.0.6 on 2020-09-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaidik_admin', '0008_auto_20200914_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='countryCode',
            field=models.CharField(default='', max_length=50),
        ),
    ]
